# https://taskfile.dev

version: "3"

tasks:
  run:
    cmds:
      # 2025-03-28 -- Only works on port 3000 for now...
      - uv run mcp dev "server.py"
      # - SERVER_PORT=10001 uv run mcp dev "server.py"

  run-prod:
    cmds:
      - uv run mcp run "server.py"
